
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module proyecto1v1(

//////////// INPUTS //////////
	BB_SYSTEM_CLOCK_50
	
);
//=======================================================
//  PARAMETER declarations
//=======================================================

	
	parameter DATAWIDTH_BUS = 32;
	parameter DATAWIDTH_DECODER_SELECTION = 3;
	parameter DATAWIDTH_ALU_SELECTION = 4;
	parameter DATAWIDTH_DECODER_OUT = 4;
	parameter DATAWIDTH_MUX_SELECTION = 3;

//=======================================================
//  PORT declarations
//=======================================================

	input 	BB_SYSTEM_CLOCK_50;

//=======================================================
//  Structural coding
//=======================================================
WB_uProcesador #(.DATAWIDTH_BUS(DATAWIDTH_BUS), 

 .DATAWIDTH_DECODER_SELECTION(DATAWIDTH_DECODER_SELECTION), 
 .DATAWIDTH_ALU_SELECTION(DATAWIDTH_ALU_SELECTION), 
 .DATAWIDTH_DECODER_OUT(DATAWIDTH_DECODER_OUT), 
 .DATAWIDTH_MUX_SELECTION(DATAWIDTH_MUX_SELECTION)) 
 
 WB_uProcesador_u0 (
  
	.WB_uProcesador_CLOCK_50(BB_SYSTEM_CLOCK_50)	
);
endmodule
